name: medstock_mobile
description: MedStock Pro - Sistema Inteligente de Gestión de Inventario Médico
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  provider: ^6.1.2

  # HTTP
  http: ^1.2.1

  # Almacenamiento seguro del JWT
  flutter_secure_storage: ^9.0.0

  # Base de datos local offline (Día 6)
  sqflite: ^2.3.3
  path: ^1.9.0

  # UI y fuentes
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0

  # Íconos extra
  iconsax: ^0.0.8

  # Gráficas (Día 5-6)
  fl_chart: ^0.68.0

  # Scanner QR (Día 3)
  mobile_scanner: ^5.1.1

  # Preferencias simples
  shared_preferences: ^2.2.3

  # Fechas
  intl: ^0.19.0

  # Íconos Material
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
